services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my_network
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

networks:
  my_network:
    driver: bridge

volumes:
  dbdata: {}
